# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

setup_permissions([
  'AppTrackingTransparency',
  'Bluetooth',
  # 'Calendars',
  # 'CalendarsWriteOnly',
  'Camera',
  # 'Contacts',
  # 'FaceID',
  # 'LocationAccuracy',
  # 'LocationAlways',
  # 'LocationWhenInUse',
  'MediaLibrary',
  'Microphone',
  # 'Motion',
  'Notifications',
  'PhotoLibrary',
  # 'PhotoLibraryAddOnly',
  # 'Reminders',
  # 'Siri',
  # 'SpeechRecognition',
  # 'StoreKit',
])



linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
  pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native'
end

target 'imeuswe' do
  config = use_native_modules!
  # Flags change depending on the env values.
  flags = get_default_flags()
  use_frameworks! :linkage => :static
  # Pods for testing 
  pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native'
  $RNFirebaseAsStaticFramework = true
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'imeuswe-UAT' do
    inherit! :complete
    # Pods for testing
    pod 'clevertap-react-native', :path => '../node_modules/clevertap-react-native'
  end

  target 'imeuswe-DEV' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => true,
    )

    installer.pods_project.targets.each do |target|
      targets_to_weaklink = ['Pods-Runner', 'agora_rtc_engine']
      frameworks_to_weaklink = [
        "AgoraAiEchoCancellationExtension",
        "AgoraAiNoiseSuppressionExtension",
        "AgoraAudioBeautyExtension",
        "AgoraClearVisionExtension",
        "AgoraContentInspectExtension",
        "AgoraDrmLoaderExtension",
        "AgoraReplayKitExtension",
        "AgoraSpatialAudioExtension",
        "AgoraSuperResolutionExtension",
        "AgoraVideoQualityAnalyzerExtension",
        "AgoraVideoSegmentationExtension"
      ]

      next unless targets_to_weaklink.include?(target.name)

      target.build_configurations.each do |config|
        base_config_reference = config.base_configuration_reference
        next if base_config_reference.nil?

        xcconfig_path = base_config_reference.real_path
        xcconfig = File.read(xcconfig_path)

        frameworks_to_weaklink.each do |framework|
          xcconfig = xcconfig.gsub(/-framework "#{framework}"/, "-weak_framework \"#{framework}\"")
        end

        File.open(xcconfig_path, "w") { |file| file << xcconfig }
      end
    end
  end
end
